name: CI

on: [push]

env:
  CI: true
  FORCE_COLOR: 3

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm test --silent -- --no-watch --verbose --run-in-band
